name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    name: checkstyle
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: download checkstyle
        run: curl -o checkstyle.jar -L https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.5/checkstyle-10.12.5-all.jar
      - name: checkstyle
        run: java -jar checkstyle.jar -c checkstyle.xml -f xml src

  test:
    name: unit test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: test
        run: mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml test
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  compile-build:
    name: compile and build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: compile
        run: mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml compile
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: build
        run: mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml jar:jar
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  deploy:
    name: deploy image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: build image
        run: |
          docker login ghcr.io --username=${{ secrets.USER_NAME }} --password=${{ secrets.ACCESS_TOKEN }}
          docker build --platform=linux/arm64 --build-arg username=${{ secrets.USER_NAME }} --build-arg password=${{ secrets.ACCESS_TOKEN }} --force-rm -t ghcr.io/slenergy-etu/slenergy/gateway-api:1.0-SNAPTSHOT .
          docker push ghcr.io/slenergy-etu/slenergy/gateway-api:1.0-SNAPTSHOT